# Generated by Django 4.2.3 on 2024-02-12 20:35

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=auth_app.models.profile_image_downloader),
        ),
    ]
