# Generated by Django 4.2.3 on 2024-03-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rename_first_name_profile_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='fullName',
        ),
    ]
