# Generated by Django 4.2.3 on 2024-06-04 19:18

import auth_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_rename_name_profile_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(blank=True, null=True, upload_to=auth_app.models.profile_image_downloader)),
                ('alt', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.avatarprofile'),
        ),
    ]
