# Generated by Django 4.2.3 on 2024-02-19 20:42

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_categories_deliverytype_payment_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=main_app.models.image_upload),
        ),
    ]
