# Generated by Django 4.2.3 on 2024-02-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_product_review_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_order',
            field=models.BooleanField(default=True),
        ),
    ]
