# Generated by Django 4.2.3 on 2024-02-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_product_options_rename_name_product_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='title',
        ),
    ]
