# Generated by Django 4.2.3 on 2024-04-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateFrom',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dateTo',
            field=models.DateField(default=None, null=True),
        ),
    ]
