# Generated by Django 4.2.3 on 2024-04-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_product_datefrom_product_dateto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
