# Generated by Django 4.2.3 on 2024-04-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_product_available_alter_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateFrom',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateTo',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
