# Generated by Django 4.2.3 on 2024-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_product_datefrom_alter_product_dateto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='free_delivery',
            new_name='freeDelivery',
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
