# Generated by Django 4.2.3 on 2024-04-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_rename_free_delivery_product_freedelivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
    ]
