# Generated by Django 4.2.3 on 2024-04-16 20:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_rename_image_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='points',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
