# Generated by Django 4.2.3 on 2024-04-22 20:05

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=main_app.models.Review),
        ),
        migrations.AlterField(
            model_name='review',
            name='points',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
