# Generated by Django 4.2.3 on 2024-04-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_alter_product_rating_alter_review_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='salePrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
