# Generated by Django 4.2.3 on 2024-04-23 16:04

from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_product_saleprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['createdAt']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_type',
            new_name='deliveryType',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='author',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='in_order',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='free_delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.TextField(null = True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.TextField(null = True, default=None, verbose_name=main_app.models.user_email),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.TextField(null = True, default=None, verbose_name=main_app.models.user_phone),
        ),
        migrations.AddField(
            model_name='order',
            name='totalCost',
            field=models.TextField(default=0, verbose_name=main_app.models.total_cost),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.specifications'),
        ),
    ]
