# Generated by Django 4.2.3 on 2024-04-23 16:06

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_specifications_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.TextField(default=None, null=True, verbose_name=main_app.models.user_phone),
        ),
    ]
