# Generated by Django 4.2.3 on 2024-04-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_alter_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='full_description',
            new_name='fullDescription',
        ),
    ]
