# Generated by Django 4.2.3 on 2024-04-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_rename_full_description_product_fulldescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='salePrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
