# Generated by Django 4.2.3 on 2024-05-06 20:37

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_alter_product_saleprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.TextField(blank=True, null=True, verbose_name=main_app.models.avg_rating),
        ),
    ]
