# Generated by Django 4.2.3 on 2024-05-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
