# Generated by Django 4.2.3 on 2024-06-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_rename_image_categories_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='subcategories',
            old_name='images',
            new_name='image',
        ),
    ]
