# Generated by Django 4.2.3 on 2024-06-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_remove_product_images_product_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': []},
        ),
        migrations.RemoveField(
            model_name='basket',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(to='main_app.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(to='main_app.review'),
        ),
    ]
