# Generated by Django 4.2.3 on 2024-06-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_alter_basket_options_remove_basket_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='main_app.review'),
        ),
    ]
