# Generated by Django 4.2.3 on 2024-06-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_alter_product_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.TextField(blank=True, null=True),
        ),
    ]
