# Generated by Django 5.0.6 on 2024-06-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_alter_product_options_alter_order_deliverytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='main_app.basket'),
        ),
    ]
