# Generated by Django 5.0.6 on 2024-06-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0047_alter_categories_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
