# Generated by Django 4.2.3 on 2024-06-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0048_basket_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='count',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='products',
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(to='main_app.product'),
        ),
    ]
