# Generated by Django 4.2.3 on 2024-06-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0050_rename_product_products_basketitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={},
        ),
        migrations.AddField(
            model_name='basketitems',
            name='archived',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='basketitems',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
