# Generated by Django 4.2.3 on 2024-06-30 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0051_alter_basket_options_basketitems_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitems',
            name='price',
        ),
        migrations.AlterField(
            model_name='basketitems',
            name='basket',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.products'),
        ),
    ]
