# Generated by Django 4.2.3 on 2024-06-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0052_remove_basketitems_price_alter_basketitems_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitems',
            old_name='basket',
            new_name='products',
        ),
    ]
