# Generated by Django 4.2.3 on 2024-07-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0054_remove_basket_products_basket_basketitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='basket',
        ),
    ]
