# Generated by Django 4.2.3 on 2024-07-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0055_rename_products_order_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.ManyToManyField(to='main_app.basketitems'),
        ),
    ]
