# Generated by Django 4.2.3 on 2024-07-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0057_rename_basket_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='baskets',
        ),
    ]
