# Generated by Django 4.2.3 on 2024-07-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0059_alter_order_totalcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.TextField(default=None, null=True),
        ),
    ]
