# Generated by Django 4.2.3 on 2024-07-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0063_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
