# Generated by Django 4.2.3 on 2024-07-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0064_alter_products_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
