# Generated by Django 4.2.3 on 2024-07-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0065_delete_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['date', 'rate']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='points',
            new_name='rate',
        ),
    ]
