# Generated by Django 4.2.3 on 2024-08-08 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0069_alter_order_deliverytype_delete_deliverytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.subcategoriesavatar'),
        ),
    ]
