# Generated by Django 4.2.3 on 2024-08-08 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0070_alter_subcategories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='subcategories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.subcategories'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.subcategoriesavatar'),
        ),
    ]
