# Generated by Django 4.2.3 on 2024-08-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0073_alter_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='categories',
            name='subcategories',
            field=models.ManyToManyField(to='main_app.subcategories'),
        ),
    ]
