# Generated by Django 4.2.3 on 2024-08-09 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0075_remove_products_category_products_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.categories'),
        ),
    ]
